version: '3.3'

services:
  react_app:
    build:
      context: ./react/talents_app
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  fastapi_backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:3006:3006"
    expose:
      - 3006
